persistence:
    file_system:
      unpreprocessed: data/unprocessed
      preprocessed: data/preprocessed
      embeddings: data/embeddings
      classification: data/classification
      models: data/classification/models
      logs: data/logs
      assets:  data/assets