from .stopwords_repository import StopwordsRepository
from .emoticon_repository import EmoticonRepository
from .tests.emoticonrepository_stub import emoticon_stub_repository
from .file_corpus_repository import FileCorpusRepository
